version: "3"

# volumes:
#   db:
#   logs:
name: vtb_backend
services:
  redis:
    image: redislabs/redismod
    ports:
      - "16379:6379"
    volumes:
      - $PWD/data:/data
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    volumes:
      - local_pg_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    # volumes:
    #   - "logs:/data"
    ports:
      - "3333:3333"
    depends_on:
      - db
      - redis
    volumes:
      - ./storage:/backend/app/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=3333"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=le"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`lctapi.onixx.ru`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
volumes:
  local_pg_data:
